lava-action: prevent fail when no permission
adevinta/lava-action pull request #21
Opened 2024-05-27 07:35 UTC by jesusfcr

2024-05-27 10:36 UTC, seilagamo approved these changes
LGTM

2024-05-30 10:22 UTC, jroimartin requested changes
Just a typo.

2024-05-30 10:22 UTC, jroimartin commented on report.js
> +      .addHeading(':warning: Unable to creeate pull request comment', 4)
```suggestion
      .addHeading(':warning: Unable to create pull request comment', 4)
```

2024-05-30 10:51 UTC, jesusfcr commented on report.js
> +      .addHeading(':warning: Unable to creeate pull request comment', 4)
done, thanks!

2024-05-30 11:06 UTC, jroimartin approved these changes
LGTM. Ready to merge. I'd tag as `v0.3.2`.

2024-05-30 11:47 UTC, merged